### ISSUE TITLE
No Commits

### ISSUE THREAD

**Issue by CoderBoyi** [teilorr/Utopiafy#1]
Percebo que constantemente o bot recebe atualizações no servidor, como correção de bugs e novos comandos, porém não há mais commits aqui no Github.
Por favor, considere o nosso Github também como lugar para compartilhar seu código e não apenas para mostrar aos outros o que você pode fazer, a vida é continuar e seguir em frente.

**Comment by teilorr** [comment]
Perfeitamente, amigo CoderBoi.

A Partir de agora, usarei o GitHub frequentemente para lhe atualizar sobre as façanhas que eu ando fazendo. Obrigado pelo lembrete!
